---
- name: zabbix agent installation...
  hosts: "{{hosts}}"
  remote_user: pi
  become: true

  tasks: 
  - name: apt update
    apt:
        update_cache: yes
    
  - name: Install the package "nmap"
    apt:
        name: nmap
  