---
- name: Upgrade Pies...
  hosts: "{{hosts}}"
  remote_user: pi
  become: true

  tasks:
  - name: clone or pull from git
    git:
        repo: https://github.com/vipulfadtedev/status-collector.git
        dest: /home/pi/scripts/status-collector
        version: main
        clone: yes 
        update: yes
  - name: cron
    cron:
        name: "collect-stats"
        user: "root"
        minute: "*/1"
        job: "sh /home/pi/scripts/status-collector/script.sh"
