---
- name: Roatate Logs...
  hosts: all
  remote_user: pi
  become: true

  tasks:
  - name: clone or pull from git
    git:
        repo: https://github.com/vipulfadtedev/rotate-logs.git
        dest: /home/pi/scripts/rotate-logs
        version: main
        clone: yes 
        update: yes
  - name: cron
    cron:
        name: "rotate-logs"
        user: "root"
        minute: "0"
        hour: "0"
        job: "sh /home/pi/scripts/rotate-logs/script.sh"
